# Generated by Django 6.0.6 on 2026-08-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_message'],
            },
        ),
    ]
