# Generated by Django 6.0.6 on 2026-08-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description_courte', models.CharField(blank=True, max_length=500)),
                ('description_complete', models.TextField(blank=True)),
                ('date_evenement', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, default='📅', max_length=10)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('programme', models.JSONField(blank=True, default=list)),
                ('intervenants', models.JSONField(blank=True, default=list)),
                ('liens_utiles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_evenement'],
            },
        ),
    ]
